### PR TITLE
Task 5 of Lesson 3

### PR DESCRIPTION
**Pull request by debeemedia**
I have completed Task Five of Lesson Three. Please review 🙏
@promise-J
@ChidiPatrick
@OgJaykay
@Pieta9221
@MiniHack @minhack
@Melumm

### CODE REVIEW

**Comment by debeemedia** [comment]
@OgJaykay

**Review by promise-J — CHANGES_REQUESTED** [review]
Great work @debeemedia. I suggest you make the image and the video to secure a full width the moment you have your first medial query.

Other than that, I am not too please with you choice of background color (although it is up to you to decide)

**Review by OgJaykay — COMMENTED** [review]
Good work 
You can merge, also you can merge final task2 too

**Review by OgJaykay — COMMENTED** [review]
Good work 
You can merge, also you can merge final task2 too

**Comment by debeemedia** [comment]
> Great work @debeemedia. I suggest you make the image and the video to secure a full width the moment you have your first medial query.
> 
> Other than that, I am not too please with you choice of background color (although it is up to you to decide)

Okay. On it.

**Comment by debeemedia** [comment]
> > Great work @debeemedia. I suggest you make the image and the video to secure a full width the moment you have your first medial query.
> > Other than that, I am not too please with you choice of background color (although it is up to you to decide)
> 
> Okay. On it.

Done.

**Pull request merged**
